on: push
name: Deploy to ECR
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: actions/docker/cli@master
      env:
        IMAGE: 445220836204.dkr.ecr.eu-west-1.amazonaws.com/etdashboard
      with:
        entrypoint: /bin/sh
        args: -c "docker build -t $IMAGE ."
    - name: Login
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: eu-west-1
        AWS_REGION: $AWS_DEFAULT_REGION
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        entrypoint: /bin/sh
        args: -c "aws ecr get-login --no-include-email | sh"
    - name: Push
      uses: actions/docker/cli@c08a5fc9e0286844156fefff2c141072048141f6
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        IMAGE: 445220836204.dkr.ecr.eu-west-1.amazonaws.com/etdashboard
      with:
        entrypoint: /bin/sh
        args: -c "docker push $IMAGE"
    - name: Deploy to Fargate
      uses: jessfraz/aws-fargate-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION: eu-west-1
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET: et-dash-action
        COUNT: "2"
        CPU: "256"
        IMAGE: 445220836204.dkr.ecr.eu-west-1.amazonaws.com/etdashboard
        MEMORY: "512"
        PORT: "8081"
